[parity]
no_download = true

[account]
unlock = ["2115df53b9358d96ff6570008e1a761c9e8ffb9a"]
password = ["/mnt/poolworkplace/poolethereumclassic/passwordether.txt"]

[ui]
disable = true

[network]
port = 30303
min_peers = 50
max_peers = 125
snapshot_peers = 50
discovery = true
max_pending_peers = 64
allow_ips = "all"

[rpc]
disable = false
port = 9545
interface = "local"
cors = "null"
apis = ["web3", "eth", "net", "parity", "rpc"]
hosts = ["none"]

[websockets]
disable = true

[ipc]
disable = false
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc"]

[dapps]
disable = true

[secretstore]
disable = true

[ipfs]
enable = false

[mining]
author = "2115df53b9358d96ff6570008e1a761c9e8ffb9a"
min_gas_price = 99000000000

[vm]
jit = false

[misc]
log_file = "/mnt/poolworkplace/parityether.log"
color = false
